name: Discord PR Notifier

on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: Ilshidur/action-discord@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            📣 Pull request ${{ github.event.action }}:
            [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }}) by ${{ github.actor }}
