name: Unreal Engine CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest  # Unreal needs Windows for building

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Unreal Engine
      uses: UnrealEngine/setup-ue@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        ue-version: 5.4  

    - name: Build Unreal Engine Project
      run: |
        & "C:\Program Files\Epic Games\UE_5.2\Engine\Build\BatchFiles\Build.bat" YourProjectEditor Win64 Development -Project="$(pwd)\YourProject.uproject" -WaitMutex -NoHotReload
      shell: pwsh

    - name: Package Project (Optional)
      run: |
        & "C:\Program Files\Epic Games\UE_5.2\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun -project="$(pwd)\YourProject.uproject" -noP4 -platform=Win64 -clientconfig=Development -cook -build -stage -pak -archive -archivedirectory="$(pwd)\PackagedBuild"
      shell: pwsh

    - name: Upload Packaged Build (Optional)
      uses: actions/upload-artifact@v3
      with:
        name: Windows-Build
        path: PackagedBuild/
